version: '2'
services:
  postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      ports:
          - 5432:5432
      volumes:
          - ./do-this-first/database_user.sql:/docker-entrypoint-initdb.d/database_user.sql
          - ./do-this-first/dwh_tables.sql:/docker-entrypoint-initdb.d/dwh_tables.sql
          - ./do-this-first/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
  webserver:
      image: puckel/docker-airflow:1.8.1
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      volumes:
          - ./etl-example/dags:/usr/local/airflow/dags
          - ./etl-example/sql:/usr/local/airflow/sql
      ports:
          - 8080:8080
      command: webserver
